### ISSUE TITLE
pcap file gets nullified after opened in pcap-mode

### ISSUE THREAD

**Issue by emacsuser123** [orgcandman/pcap-mode#4]
Hi.

With the last commit, I'm able to open pcap files successfully.
I can also open individual packets using RET on each.

But when I try to apply a simple filter, for instance, frame.number == 1, no message appears, and the whole pcap file gets truncated to 0 bytes, even though I answer "No" to the question "Do you want to save the file?".

Any operation that I try to perform gives me the following error:
pcap-mode-cleanup: Symbol's value as variable is void: pcap-packet-cleanup-list

I presume that error comes because the file is already truncated to 0 bytes by pcap-mode.

In fact, I cannot leave emacs with C-x c, since I get that error all the time, even when my current buffer is not the pcap-mode buffer.

Thanks.
-Bob

**Comment by apconole** [comment]
okay, let me try to reproduce - that hadn't been causing a problem for me.  What about when you press 't' ?

**Comment by apconole** [comment]
Okay, I think I have it fixed.  Try again with the latest commit. If it's working, please close :)

**Comment by emacsuser123** [comment]
Hi.

It is working fine now. Thanks a lot.

May I suggest an enhancement/new feature?
It would be nice to have the possibility of viewing/opening a bunch of packets on the view buffer at the same time. Maybe putting a certain packet separator between packets or so.

Thanks a lot and regards.
-Bob
